---
# basic configuration
use-singularity: true
use-conda: true

# these control where the images are stored.  If you have a central location
# you don't have to remake images when changing working directory
# Alternatively you can set the shadow-prefix for the entire .snakemake dir
singularity-prefix: "~/snakemake_images"
conda-prefix: "~/snakemake_images"

# cluster specific settings
cluster: "sbatch --cpus-per-task={threads} --mem={resources.mem}M\
            --time={resources.time} --output=slurm_out/%x-%A\
            --job-name={rule} --parsable"
cluster-status: "slurm-status.py"
latency-wait: 120  # wait 2 minutes for missing files before raising exception
                   # important for NFS
jobs: 250  # maximum jobs to run at once
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 4  # maximum local jobs to run
resources: short_jobs=2  # custom resources, prevents tying up queue with short
                         # qos jobs
